version: '3.0'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: ./backend/.env.example
    container_name: kupipodariday-backend
    ports:
      - '4000:3000'
    depends_on:
      - database
    restart: always
    networks:
      - database
      - default

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: kupipodariday-frontend
    ports:
      - "8081:80"
    restart: always

  database:
    image: postgres:12
    container_name: kupipodariday-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-student}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-student}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_DB: ${POSTGRES_DB:-kupipodariday}
    volumes:
      - pgdata:${POSTGRES_PGDATA:-/var/lib/postgresql/data}
    restart: always
    networks:
      - database

volumes:
  pgdata:

networks:
  database:
    driver: bridge
